---
- name: Manage cybera-dotfiles git repository
  ansible.builtin.git:
    repo: "{{ cybera_dotfiles_repo }}"
    dest: /root/cybera-dotfiles
    version: "{{ cybera_dotfiles_version }}"
    force: yes
  notify: Install dotfiles
